"""change price scale to 2

Revision ID: e4865aa9c146
Revises: 17f51225672e
Create Date: 2026-05-19 15:17:34.967899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4865aa9c146'
down_revision: Union[str, Sequence[str], None] = '17f51225672e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'price',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'price',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=18, scale=8),
               existing_nullable=False)
    # ### end Alembic commands ###
